export default [
    { britFact: "London has more foreigners than any other city in Europe." },
    { britFact: "Each London bus travels about 12,000 kilometers a year." },
    { britFact: "The United Kingdom consists of four countries: England, Scotland, Wales and Northern Ireland." },
    { britFact: "The British have a word for it: “gobsmacked” – it means “struck so much that one is speechless”." },
    { britFact: "The oldest operating pub in Britain is Ye Olde Fighting Cocks, which has been operating since the 9th century." },
    { britFact: "London was the first city in the world to have a subway (1863)." },
    { britFact: "Queen Elizabeth II owned dolphins, whales and all the fish in British waters – this is legally enshrined." },
    { britFact: "English tea is so popular that the country consumes over 60 billion cups a year." },
    { britFact: "In England, eating pies was once banned – in the 16th century, due to “excessiveness”." },
    { britFact: "Scotland has its own national monster, Loch Ness." },
    { britFact: "There are over 20,000 red telephone boxes in London, most of which are no longer in use, but are protected as historical heritage." },
    { britFact: "Shakespeare coined over 1,700 new words for the English language." },
    { britFact: "Poetry is a compulsory subject in British schools." },
    { britFact: "The most popular name for British cats is Charlie." },
    { britFact: "About 80 umbrellas are lost on the London Underground every day." },
    { britFact: "Britain has no official written constitution." },
    { britFact: "The Scots have their own patron saint's day, St. Andrew's Day." },
    { britFact: "Security cameras film the average Londoner about 300 times a day." },
    { britFact: "Big Ben is not a tower, but a bell inside it." },
    { britFact: "The first police station opened in London in 1829." },
    { britFact: "The inhabitants of Wales speak two languages ​​- Welsh and English." },
    { britFact: "In Britain, people drive on the left side of the road - only 30% of the world's countries do the same." },
    { britFact: "The Tower of London was once a fortress, a prison, and even a zoo." },
    { britFact: "British houses often do not have a light switch in the bathroom - for safety reasons." },
    { britFact: "The British were the first in the world to come up with life insurance." },
    { britFact: "Every day, Big Ben deviates from the exact time by no more than 2 seconds." },
    { britFact: "There are more than 15 thousand castles and fortresses in Britain." },
    { britFact: "Every third British house was built before World War II." },
    { britFact: "The most favorite dish of the British is not fish and chips, but chicken \"tika masala\"." },
    { britFact: "The English often greet each other not with words, but with the question \"Are you alright?\" - even if they are not interested." }
]